### ISSUE TITLE
Päättäkää harkkatyön aihe.

### ISSUE THREAD

**Issue by putsi** [putsi/KayttisHarkka#1]
Tässä @putsi:n aihe-ehdotus vielä muistutukseksi:

> Ehottasin ryhmätyön aiheeks allaolevaa:

> Toteuta linuxiin kernelin moduuli (lkm), jolle lähetetään dataa merkkilaitteen (character device) avulla, ajuri muokkaa dataa ja se voidaan lukea muuttuneena takaisin toisesta prosessista. Muokkaus voi olla esim. datan salaaminen (salausavain asetetaan ajurin latauksen yhteydessä tai dynaamisesti IOCTL-kutsulla). Tutkielmassa kerrottava tarkka selostus merkkiajurien toiminnasta linux:ssa.

> tai ylinpäätänsä jotain noista kernel-moduulin tai inotyfysoftan toteuttamisista

**Comment by sandstro** [comment]
Mua vois kyl kiinnostaa kans tuo aihe, salauksen toteutus vois olla tosiaan hyvä lähtökohta tähän. Se ois alustavasti ainakin kiinnosta. Mähän en kyllä linuxista oikein mitään tiedä tai muutenkaan käyttöjärjestelmistä, mutta tässähän se selviää sitten..

**Comment by sandstro** [comment]
docker vois kiinnostaa myös

**Comment by sandstro** [comment]
Itseasiassa docker kiinnostaa kaikkein eniten kun voi tulla eteen kyseisen tuotteen käyttö työtehtävissä. Mutta käy mulle muutkin :D

**Comment by putsi** [comment]
Dockeri vähä tylsän olonen ku siinä pitää tehä vaan esittely eikä mitään toteutusta

**Comment by sandstro** [comment]
Nojoo, voishan siihen tehdä ihan kunnon setupin. Laittaa railsia ajoo tms. Mutta sopii mulle tosiaan noi kerneli hommatkin! :)

**Comment by putsi** [comment]
Tuli muuten mieleen että tän harkkatyönhän vois periaatteessa yhistää myös turvallisen ohjelmoinnin kurssin harkkatyöhon.

**Comment by putsi** [comment]
Vissiin teemme Dockerista.
