### ISSUE TITLE
Työn sisällön ja rakenteen suunnittelu

### ISSUE THREAD

**Issue by putsi** [putsi/KayttisHarkka#2]
Tähän vois jotain kommentteja sisällöstä ja rakenteesta laittaa?

**Comment by sandstro** [comment]
Tässä jotain resursseja joista vois rajata/spekstata tarkemmin:
- Erityisesti cgroups ja union file systems https://docs.docker.com/introduction/understanding-docker/
- Perus docsit löytyy https://docs.docker.com/userguide/

**Comment by sandstro** [comment]
LXC:stä on myös paljon hyvää kirjoiteltu, sitä vois tutkia myös

**Comment by putsi** [comment]
Ihan perus perusteet/kuvaukset softasta ja joku case käyttöönotosta kans vois olla

**Comment by sandstro** [comment]
Juup, samoin toiminta Linux vs. OS X, koska OS X:llä out-of-the-box toimii hitaasti/heikosti kun taas Linuxilla pyörii mainiosti. Vois selvittää vähän syitä tuohon?
